from pofile import *
from qt import *
from javaproperties import *
from dtd import *
from joomla_ini import *
from desktop import *
from strings import *
from xliff import *
from wiki import *
from pseudo import *
from validators import *
from info import *
from registry import *